# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: mqtt-device-service # NOTE: update this with your service name
tenant: rostykromanyshyn
app: well-sensor

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}

functions:
  healthCheck:
    handler: handler.healthCheck
    events:
      - http:
          path: /
          method: get
          cors: true

  getAllMqttServers:
    handler: handler.getAllMqttServers
    events:
      - http:
          path: mqtt-servers
          method: get
          cors: true

  saveMqttServer:
    handler: handler.saveMqttServer
    events:
      - http:
          path: mqtt-servers/{id}
          method: put
          cors: true
      - http:
          path: mqtt-servers
          method: put
          cors: true

  getMqttUsers:
    handler: handler.getMqttUsers
    events:
      - http:
          path: mqtt-servers/{id}/mqtt-users
          method: get
          cors: true

  saveMqttUser:
    handler: handler.saveMqttUser
    events:
      - http:
          path: mqtt-users/{id}
          method: put
          cors: true
      - http:
          path: mqtt-users
          method: put
          cors: true

  getMqttDevices:
    handler: handler.getMqttDevices
    events:
      - http:
          path: mqtt-users/{id}/mqtt-devices
          method: get
          cors: true

  saveMqttDevice:
    handler: handler.saveMqttDevice
    events:
      - http:
          path: mqtt-devices/{id}
          method: put
          cors: true
      - http:
          path: mqtt-devices
          method: put
          cors: true

plugins:
  - serverless-offline
